Repository RobTheFiveNine/company-icons, pull requests merged in 2022-10, with the labels that each got.

#2 Improve codebase to allow easier collaboration
  .pnp.cjs
  .yarn/cache/@jridgewell-source-map-npm-0.3.2-6fd1f37b22-1b83f0eb94.zip
  .yarn/cache/@types-html-minifier-terser-npm-6.1.0-707ea07fcb-eb843f6a8d.zip
  .yarn/cache/boolbase-npm-1.0.0-965fe9af6d-3e25c80ef6.zip
  .yarn/cache/camel-case-npm-4.1.2-082bf67a9a-bcbd25cd25.zip
  .yarn/cache/clean-css-npm-5.3.1-e052e24a9f-860696c605.zip
  .yarn/cache/commander-npm-8.3.0-c0d18c66d5-0f82321821.zip
  .yarn/cache/css-select-npm-4.3.0-72f53028ec-d620273683.zip
  .yarn/cache/css-what-npm-6.1.0-57f751efbb-b975e547e1.zip
  .yarn/cache/dom-converter-npm-0.2.0-902408f4a0-ea52fe303f.zip
  .yarn/cache/dom-serializer-npm-1.4.1-ebb24349c1-fbb0b01f87.zip
  .yarn/cache/domelementtype-npm-2.3.0-02de7cbfba-ee837a318f.zip
  .yarn/cache/domhandler-npm-4.3.1-493539c1ca-4c665ceed0.zip
  .yarn/cache/domutils-npm-2.8.0-0325139e5c-abf7434315.zip
  .yarn/cache/dot-case-npm-3.0.4-09675b5521-a65e351941.zip
  .yarn/cache/entities-npm-2.2.0-0fc8d5b2f7-19010dacaf.zip
  .yarn/cache/gh-pages-npm-3.2.3-de723c58be-0a6e92180c.zip
  .yarn/cache/gh-pages-npm-4.0.0-1490bfc5d9-255648eb27.zip
  .yarn/cache/he-npm-1.2.0-3b73a2ff07-3d4d6babcc.zip
  .yarn/cache/html-minifier-terser-npm-6.1.0-49a405eebd-ac52c14006.zip
  .yarn/cache/html-webpack-plugin-npm-5.5.0-75c5a14e55-f3d84d0df7.zip
  .yarn/cache/htmlparser2-npm-6.1.0-4ef89ab31e-81a7b3d9c3.zip
  .yarn/cache/lower-case-npm-2.0.2-151055f1c2-83a0a5f159.zip
  .yarn/cache/no-case-npm-3.0.4-12884c3d98-0b2ebc113d.zip
  .yarn/cache/nth-check-npm-2.1.1-f97afc8169-5afc3dafcd.zip
  .yarn/cache/param-case-npm-3.0.4-cfb242ad97-b34227fd0f.zip
  .yarn/cache/pascal-case-npm-3.1.2-35f5b9bff6-ba98bfd595.zip
  .yarn/cache/pretty-error-npm-4.0.0-7cca1fe4ad-a5b9137365.zip
  .yarn/cache/relateurl-npm-0.2.7-7687cc0a2a-5891e792ea.zip
  .yarn/cache/renderkid-npm-3.0.0-acb028643f-77162b62d6.zip
  .yarn/cache/source-map-support-npm-0.5.21-09ca99e250-43e98d700d.zip
  .yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip
  .yarn/cache/terser-npm-5.15.0-a7f79b7859-b2358c989f.zip
  .yarn/cache/utila-npm-0.4.0-27b344403b-97ffd3bd2b.zip
  CONTRIBUTING.md
  __tests__/components/App.test.jsx
  __tests__/components/__snapshots__/App.test.jsx.snap
  bin/minify-icons.js
  logos/icons.json
  logos/icons.mini.json
  package.json
  src/components/App.jsx
  src/icons.json
  src/index.html
  webpack.common.config.js
  webpack.dev.config.js
  webpack.prod.config.js
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#6 Solves #3: Making icon count dynamic
  __tests__/components/__snapshots__/App.test.jsx.snap
  src/components/App.jsx
  src/components/IconSelect.jsx
  src/index.html
Labels: hacktoberfest-accepted

#8 added to the icon library
  logos/NASDAQ-GASS.jpg
  logos/NASDAQ-MITO.png
  logos/NASDAQ-MOB.png
  logos/NASDAQ-TUEM.jpg
  logos/NYSE-TTE.jpg
  src/icons.json
Labels: hacktoberfest-accepted

#14 Apply security patches suggested by Dependabot
  .pnp.cjs
  .yarn/cache/@emotion-babel-plugin-npm-11.10.2-5ade7f379a-7f9e84b3c0.zip
  .yarn/cache/@emotion-cache-npm-11.10.3-77f93c9eba-d31291eff1.zip
  .yarn/cache/@emotion-hash-npm-0.8.0-0104f4bbf3-4b35d88a97.zip
  .yarn/cache/@emotion-hash-npm-0.9.0-efbc0b3f3f-b63428f7c8.zip
  .yarn/cache/@emotion-memoize-npm-0.8.0-c5dd451828-c87bb110b8.zip
  .yarn/cache/@emotion-react-npm-11.10.4-00a955a9fe-7555f6a184.zip
  .yarn/cache/@emotion-react-npm-11.4.1-2f2428bc17-de3c215078.zip
  .yarn/cache/@emotion-serialize-npm-1.0.2-a692afdb82-ff84fbe09e.zip
  .yarn/cache/@emotion-serialize-npm-1.1.0-492b26b387-8f22f83194.zip
  .yarn/cache/@emotion-sheet-npm-1.2.0-3bb8dd5fba-b3771e4796.zip
  .yarn/cache/@emotion-unitless-npm-0.7.5-14e1171640-f976e5345b.zip
  .yarn/cache/@emotion-unitless-npm-0.8.0-aa125284fa-176141117e.zip
  .yarn/cache/@emotion-use-insertion-effect-with-fallbacks-npm-1.0.0-d02a7659c4-4f06a3b482.zip
  .yarn/cache/@emotion-utils-npm-1.2.0-337992f692-55457a49dd.zip
  .yarn/cache/@emotion-weak-memoize-npm-0.3.0-705bdd075b-f43ef4c8b7.zip
  .yarn/cache/@types-parse-json-npm-4.0.0-298522afa6-fd6bce2b67.zip
  .yarn/cache/@types-prop-types-npm-15.7.5-2aa48aa177-5b43b8b154.zip
  .yarn/cache/@types-react-npm-18.0.21-e933f9864e-36c1a7c9d5.zip
  .yarn/cache/@types-react-transition-group-npm-4.4.5-8f92107b07-265f1c7406.zip
  .yarn/cache/@types-scheduler-npm-0.16.2-ba3a7d8c68-b6b4dcfeae.zip
  .yarn/cache/axios-npm-0.21.1-d192f6b3b3-c87915fa0b.zip
  .yarn/cache/axios-npm-0.27.2-dbe3a48aea-38cb754046.zip
  .yarn/cache/babel-plugin-macros-npm-3.1.0-320e781f4e-765de4abeb.zip
  .yarn/cache/cosmiconfig-npm-7.0.1-dd19ae2403-4be63e7117.zip
  .yarn/cache/follow-redirects-npm-1.15.2-1ec1dd82be-faa66059b6.zip
  .yarn/cache/react-dom-npm-17.0.2-f551215af1-1c1eaa3bca.zip
  .yarn/cache/react-dom-npm-18.2.0-dd675bca1c-7d323310be.zip
  .yarn/cache/react-input-autosize-npm-3.0.0-c2fd3b468a-cc3309ddc8.zip
  .yarn/cache/react-is-npm-17.0.2-091bbb8db6-9d6d111d89.zip
  .yarn/cache/react-npm-17.0.2-99ba37d931-b254cc17ce.zip
  .yarn/cache/react-npm-18.2.0-1eae08fee2-88e38092da.zip
  .yarn/cache/react-select-npm-4.3.1-5d01b98ddd-e87e0b42a6.zip
  .yarn/cache/react-select-npm-5.4.0-c9d9dbc71a-da896f0f8b.zip
  .yarn/cache/react-select-virtualized-npm-3.5.0-bd82f61c88-2b18fd418e.zip
  .yarn/cache/react-select-virtualized-npm-5.2.0-41cb3161fc-2500b7ef15.zip
  .yarn/cache/react-shallow-renderer-npm-16.14.1-b8a4f845ff-f344c663c4.zip
  .yarn/cache/react-shallow-renderer-npm-16.15.0-cf95219885-6052c7e3e9.zip
  .yarn/cache/react-test-renderer-npm-17.0.2-1086717127-e6b5c6ed2a.zip
  .yarn/cache/react-test-renderer-npm-18.2.0-cdc6051330-6b6980ced9.zip
  .yarn/cache/scheduler-npm-0.20.2-90beaecfba-c4b35cf967.zip
  .yarn/cache/scheduler-npm-0.23.0-a379a6bc3b-d79192eeaa.zip
  .yarn/cache/stylis-npm-4.0.13-3f245d840f-8ea7a87028.zip
  .yarn/cache/yaml-npm-1.10.2-0e780aebdf-ce4ada136e.zip
  __tests__/components/__snapshots__/App.test.jsx.snap
  package.json
  yarn.lock
Labels: bug

#13 adding computershare logo to library
  logos/NASDAQ-CMSQF.png
  src/icons.json
Labels: hacktoberfest-accepted

#15 Added comma to the count of the number of icons
  src/components/App.jsx
Labels: enhancement, hacktoberfest-accepted
